### PR TITLE
Xiyue update UI

### PR DESCRIPTION
**Pull request by xiyuewang556633**
# Overview

Updated UI by adjusting the button locations and button descriptions, along with descriptions.

# Please leave comment if you think there are other possible optimizations or you think the old version is better

# Details
## Before:
Screen Shot 2022-03-07 at 1 07 07 PM

## After:
image

### CODE REVIEW

**Review by vChase42 — DISMISSED** [review]
LGTM, I think this new GUI looks better.

**Comment by pconrad** [comment]
@xiyuewang556633 I've made a Pull Request to your branch with some changes that I'd like to suggest.

https://github.com/ucsb-cs156-w22/team04-w22-7pm-HappyCows/pull/44

I did this because I wanted to make sure they would work on Heroku (for some reason, I couldn't get the images to show up on localhost; neither with your code nor my code, but I think that's a localhost issue on my computer.)

If you are willing to accept these changes, please merge pull request 44 (I think you can do that since it isn't a pull request to a protected branch; if you can't let me know.)

**Review by pconrad — CHANGES_REQUESTED** [review]
Please remove this section from the PR description:

```
Reminders (delete this section before merging or as code is merged)

Explicitly link to this pull request each issue that it closes
Assign one and ideally two reviewers to review this pull request.
Reviewers should not just approve with "Looks good!" Instead, reviewers should carefully go through the code and use GitHub's reviewer interface to ask questions, make comments, and suggest changes.
```

Also, consider merging in my PR here into yours: 

https://github.com/ucsb-cs156-w22/team04-w22-7pm-HappyCows/pull/44

**Review by pconrad — APPROVED** [review]
LGTM... as soon as the CI/CD tests complete, I think I can merge this for 10 points.

**Comment by pconrad** [comment]
Merging for 10 points in spite of codecov report; the files that are added here have 100% coverage, so it's not clear why codecov is complaining.

**Pull request merged**
