### PR TITLE
Xiyue hide view and join buttons from strangers

### LINKED ISSUE #59: Do not show Join or Visit buttons on home page when use is not logged in
On the home page, we can see the list of commons that exist when the user is not logged in.

That's fine, but the "Join" buttons should be either hidden, or disabled.

Further if you log out, the Visit buttons are still there.  When you log out, this list of commons you are a part of should go away, and the visit buttons should disappear

# Existing Problem

This screen shot illustrates the problem:

image

### PR DESCRIPTION
**Pull request by xiyuewang556633**
# Overview

Hide view and join buttons from strangers. The list of existing commons can still be seen though.

# Issues Addressed

Closes #59

# Details

https://user-images.githubusercontent.com/59850013/157933897-dcef410b-5992-427f-8492-997a147ee679.mov

### CODE REVIEW

**Review by isaacchin — APPROVED** [review]
Works as intended, I tried to see if there was a way to hide this container 
image
when logged out, but it would render the entire HomePage blank for some reason. This is probably a good enough solution for now.

**Review by pconrad — DISMISSED** [review]
LGTM... will test on Heroku before merging

**Comment by xiyuewang556633** [comment]
#Update

Now the established commons are hidden from logged out users as well.

# Details 
## This video is a comprehensive presentation of frontend displaying functionalities

https://user-images.githubusercontent.com/59850013/157987815-2f3fcda6-aa9d-4f19-966a-fd801785032b.mov

**Review by vChase42 — APPROVED** [review]
LGTM

**Review by vChase42 — APPROVED** [review]
LGTM

**Review by bzamora020 — APPROVED** [review]
Works as expected on Heroku. LGTM

**Pull request merged**
