### PR TITLE
W22 7pm 3 Profits Table Displays profits

### PR DESCRIPTION
**Pull request by vChase42**
# Overview

ProfitsTable no longer uses dummyData and displays profits. 
Added tests.
Added storybook.

# Issues Addressed

#49 

# Details

image

To test, you must add data manually through profits endpoint.
image

### CODE REVIEW

**Review by isaacchin — DISMISSED** [review]
Deployed and tested on Heroku, works pretty well. 
image
LGTM

**Review by xiyuewang556633 — APPROVED** [review]
Works as described. LGTM

**Review by pconrad — APPROVED** [review]
LGTM

**Review by xiyuewang556633 — APPROVED** [review]
LGTM.

**Review by bzamora020 — APPROVED** [review]
LGTM! Tested on Heroku

**Pull request merged**
