### PR TITLE
W22 7pm 4 sy og edit common

### PR DESCRIPTION
**Pull request by oliviagillam**
# Overview
Merge PR #63 before merging this one
Added Edit functionality (for admins)

- Created edit page
    - prefills with data
    - checks data
    - updates data
- Created edit page tests
- Changed the CreateCommonsForm to get that to work with both Edit Page and CreatePage 
     - changes onSubmit to submitAction 
     - Added cancel button
- Changed  the CreateCommonsForm Tests because changing the form messed up the tests
- App.js

# Issues Addressed

Addresses issue #7

# Details
has prefilled data entry

image

reroutes to list page with a toast message that confirms that it worked 
image

### CODE REVIEW

**Review by simonyu01 — APPROVED** [review]
Looks good!

**Review by allisonhuang2 — APPROVED** [review]
looks good on heroku. thanks for being thorough and taking on such a big task

**Review by allisonhuang2 — APPROVED** [review]
LGTM

**Review by pconrad — APPROVED** [review]
LGTM

**Pull request merged**
