### PR TITLE
W22 7pm 4 sy og edit backend

### PR DESCRIPTION
**Pull request by simonyu01**
Added PUT endpoint for editing a common and wrote tests for backend. 

Addresses issue [#64](https://github.com/ucsb-cs156-w22/team04-w22-7pm-HappyCows/issues/64)

Information in commons before editing:
image

Information in commons after editing:
image

### CODE REVIEW

**Review by oliviagillam — APPROVED** [review]
Checked on local and it works LGTM

**Review by allisonhuang2 — APPROVED** [review]
tried it out on heroku and it works. ty

**Review by oliviagillam — APPROVED** [review]
I didnt realize that I have to review again after fixing merge conflicts

**Review by pconrad — APPROVED** [review]
LGTM

**Pull request merged**
