### PR TITLE
Xiyue Display Selling and Buying price in frontend

### PR DESCRIPTION
**Pull request by xiyuewang556633**
# Overview

Displayed Selling price next to the Market price. Also updated the formula for the Selling price in the note section. The prices will be automatically populated when creating a user common. See the video for a use.

# Issues Addressed
#30

# Details
## Before:
image

## After:

https://user-images.githubusercontent.com/59850013/157505158-c30ea0c7-1d0f-4e97-af7b-76f8fa7f3bfa.mov

### CODE REVIEW

**Review by vChase42 — APPROVED** [review]
LGTM

**Review by isaacchin — CHANGES_REQUESTED** [review]
There is no cowPrice variable in the Commons entity, might have to set that up in the backend first

**Review by isaacchin — APPROVED** [review]
Looks good now that the cow price exists in the Commons entity

**Review by thomashale-ucsb — APPROVED** [review]
LGTM, I'll add zamora onto this PR if he isn't already on

**Review by vChase42 — APPROVED** [review]
LGTM

**Review by pconrad — DISMISSED** [review]
LGTM

**Comment by pconrad** [comment]
Deploying here: https://dashboard.heroku.com/apps/team04-w22-7pm-3/deploy/github

**Review by vChase42 — APPROVED** [review]
LGTM

**Pull request merged**
