### PR TITLE
W22-7pm-3 ca avg cow health

### LINKED ISSUE #20: EPIC03 - Display Cow Health for a user's commons
# Acceptance Criteria:
- [x] Change Cow Health to Average Cow Health in the user interface
- [x] Get average cow health for a user's commons from the backend using some API get endpoint (look at backend code to figure it out)
- [x] Display average cow health for a user's commons in the frontend

### PR DESCRIPTION
**Pull request by vChase42**
# Overview

Added avgCowHealth to backend and to the display on frontend. Added tests

# Issues Addressed

Closes #20 

# Details

image

### CODE REVIEW

**Comment by vChase42** [comment]
This version of Happy-Cows has a new variable in userCommons, with conflicts with previous userCommons that already exist in the database.
Use `heroku pg:reset --app team04-w22-7pm-3-qa` to reset heroku databse

**Review by xiyuewang556633 — APPROVED** [review]
Works on Heroku QA. LGTM
image

**Review by mglush — APPROVED** [review]
Works on QA, doesn't change test coverage, LGTM.

**Review by pconrad — APPROVED** [review]
LGTM.. just waiting on CI/CD

**Comment by pconrad** [comment]
Deploying here: https://dashboard.heroku.com/apps/team04-w22-7pm-3-qa/deploy/github

**Comment by pconrad** [comment]
I deployed this to Heroku:

image

This is what happened when I tried it:

**Review by bzamora020 — APPROVED** [review]
Looks good to me! This is how it shows on Heroku

image

image

**Pull request merged**
