### PR TITLE
Xiyue Display numPlayers, numCows, milkPrice, dates on PlayPage

### LINKED ISSUE #30: EPIC03 - Display market cow price (buy and sell price) in the frontend works

### PR DESCRIPTION
**Pull request by xiyuewang556633**
# Overview
This PR makes frontend to display numPlayers, numCows, milkPrice, start&endDate on the PlayPage.

Specifically, these fields are added to commons entity as private variables.

# Issues Addressed

Closes #30, #31, #16

# Details
image

### CODE REVIEW

**Review by pconrad — CHANGES_REQUESTED** [review]
Instead of  the title  "display many stuffs" how about:

Display numPlayers, numCows, milkPrice, start &endDate on ____

Fill in the blank with what page or component it appears in.

Or: "Add commons fields to _____" where ___ is the name of the component or page.

**Review by pconrad — CHANGES_REQUESTED** [review]
Should the .png files being deleted here really be deleted?

I'm not sure... let me know.

**Review by vChase42 — DISMISSED** [review]
LGTM, Xiyue made a separate PR for populating end date.

**Review by pconrad — APPROVED** [review]
LGTM-but will want to test on Heroku before merging

**Review by vChase42 — APPROVED** [review]
LGTM

**Review by bzamora020 — APPROVED** [review]
Tested on Heroku QA and main. Works well.

**Pull request merged**
